version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: crossproduct-db
    environment:
      POSTGRES_USER: crossproduct-user
      POSTGRES_PASSWORD: crossproduct-pass
      POSTGRES_DB: crossproduct-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
